[package]
name = "typst-upgrade"
version = "0.2.0"
edition = "2021"
authors = ["coekjan <cn_yzr@qq.com>"]
license = "MIT"
description = "A tool to upgrade typst packages"
repository = "https://github.com/Coekjan/typst-upgrade"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env", "suggestions", "string"] }
regex = "1.10.4"
reqwest = { version = "0.12.3", features = ["blocking", "json"] }
semver = "1.0.22"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
toml = "0.8.12"
typst-syntax = "0.11.0"
